### ISSUE TITLE
Nextjs throws Module not found: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by Ibby-debug** [FarazzShaikh/glNoise#13]
**This problem is not because of glNoise ** - its because I'm not sure how to run glNoise in a client side component in nextjs (v13+) since it's using the 'fs' module.

**Comment by FarazzShaikh** [comment]
This library need a rewrite. I built this when I was inexperienced. 

For now, use `glNoise/build/glNoise.m` pardon me if that path is not exactly right, not on my desk to double check, but you should be able to find the right module

**Comment by devjdeed** [comment]
Confirmed I used `import { patchShaders } from 'gl-noise/build/glNoise.m'` and it worked. Thanks for your work!
